#
# Copyright 2019-2020 DJANTA, LLC (https://www.djanta.io)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed toMap in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Deploy

on:
  create:
    tags:
      - /^((rc|v|version|release|tag)(-)?)?([0-9\.]+)((-)?(patch|beta|alpha))?$/
    branches:
      - 'refs/tags/*'
      - '!refs/heads/*'
jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
 #       jdk: [8, 9, 10, 11]
 #       version: [7.10, 8.10, 9.10, 10.10]
 #       registry: [/*gcr.io*/ /*,docker.pkg.github.com*/]
    steps:
      - name : GITHUB CONTEXT
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          export PATCH=$(date -u +'%m')
          echo "$GITHUB_CONTEXT"
          echo "Patch: $PATCH"